### ISSUE TITLE
Question: backport some rct3 track pieces? 

### ISSUE THREAD

**Issue by Ryder17z** [X123M3-256/RCT2RideGenerator#21]
You may or may not be aware of these pieces, but I would like to at least attempt to make them at some point, unless someone else beats me to it.

I'm not sure if it is looping or corkscrew coaster that has the pieces that I'd like to port, I'll have to check up on it. 

Anyway they are;

Tilt section: straight to vertical drop
Elevator lift hill (lifts the whole train up)
Elevator lift hill top: vertical drop transition (from the piece listed above)	

I do realize that these pieces won't be easy to work on, but I am more interested in the idea of trying.

**Comment by X123M3-256** [comment]
This project is a program that creates custom rides for RCT2 - since you're requesting a feature to be added to the game it should be posted on the OpenRCT2 Github page. Since it doesn't pertain to this project, I'll close the issue, but you could repost it there if you want the OpenRCT2 developers to comment on it.

Adding new elements to the game will not be possible without a new save format. For this reason, I haven't looked into how to do it. I believe that that the process of adding a basic track piece would be similar to that of adding a track style - some constants would need updating, and some functions implemented, but nothing fundamental needs to change.

But these elements would require the track itself to animate, and no existing track piece in the game does - so this is new functionality that would have to be implemented. If you want to experiment with this, I would try something more basic first - like a diagonal brake piece.

**Comment by ExileFox** [comment]
Thanks for the info. I do realize that it wouldn't be easy, but it might be
possible like through a plugin or other extension.
